config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :hoods, only: [:index, :show] do
    resources :contracts, only: [:new, :create]
  end
  resources :contracts, only: [:show, :index, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  belongs_to :hood
  has_one_attached :photo
  validates :name, presence: true
  validates_inclusion_of :violence_required, :in => 0..3
end

app/models/hood.rb
class Hood < ApplicationRecord
  has_many :contracts
  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :skills, presence: true
  validates :price, presence: true

  def self.search(search)
    where("city ILIKE ?", "%#{search}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contracts
  has_many :hoods, through: :contracts

  validates :name, presence: true
  validates :city, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :city])
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_hood, only: [:new, :create]
  before_action :set_contract, only: [:show, :destroy]
  def index
    @contracts = Contract.all
  end

  def show
    @hood = @contract.hood
  end

  def new
    @contract = Contract.new
  end

  def create
    @contract = Contract.new(contract_params)
    @contract.user = current_user
    @contract.hood = @hood
    if @contract.valid?
      @contract.save!
      redirect_to contract_path(@contract)
    else
      render :new
    end
  end

  def destroy
    @contract.user = current_user
    @contract.hood = @hood
    @contract.destroy
    redirect_to contracts_path
  end

  private

  def set_contract
    @contract = Contract.find(params[:id])
  end

  def set_hood
    @hood = Hood.find(params[:hood_id])
  end

  def contract_params
    params.require(:contract).permit(:name, :description, :date, :violence_required, :location, :photo)
  end
end

app/controllers/hoods_controller.rb
class HoodsController < ApplicationController

  def index
    @hoods = Hood.search(params[:search])
    if params[:query].present?
      @hoods = Hood.search(params[:search]).where(violence_range: params[:query])
    end
    if params[:query_price].present? && params[:query_price] == "1"
      @hoods = Hood.search(params[:search]).order(price: :asc)
    end
    if params[:query_price].present? && params[:query_price] == "2"
      @hoods = Hood.search(params[:search]).order(price: :desc)
    end
  end

  def show
    @hood = Hood.find(params[:id])
  end

  def hoods_params
    params.require(:hood).permit(:query)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1542367235-d0f3b564d16e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2089&q=80);">
  <div class="container ">
    <h1><strong>Contracts</strong></h1>
    <p>You sign them, we break teeth for you</p>
    <div class="d-flex align-items-end flex-column bd-highlight mb-3">
      <div class="mt-auto p-2 bd-highlight">
      </div>
    </div>
  </div>
</div>
<div class="body-contrat">
  <table class="center">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Location</th>
        <th>Violence Required</th>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contracts.each do |contract| %>
        <tr>
          <td><%= contract.name.capitalize %></td>
          <td><%= contract.date %></td>
          <td><%= contract.location.capitalize %></td>
          <td class="lvl-violence">
            <% if (3 - contract.violence_required) != 0 %>
              <% contract.violence_required.times do %>
                <i class="fas fa-tint"></i>
              <% end %>
              <% (3 - contract.violence_required).times do %>
                <i class="fas fa-tint drop-vide"></i>
              <% end %>
            <% else %>
              <% 3.times do %>
                <i class="fas fa-tint"></i>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "Show", contract_path(contract), class:"btn btn-secondary my-2" %></td>
          <td>
            <%= link_to contract_path(contract), method: :delete,
              data: { confirm: "Are you sure?" } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>


    </tbody>
  </table>
</div>

<br>

app/views/contracts/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1542367235-d0f3b564d16e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2089&q=80);">
  <div class="container ">
    <h1><strong>New Target</strong></h1>
    <p>Give us some informations</p>
    <div class="d-flex align-items-end flex-column bd-highlight mb-3">
      <div class="mt-auto p-2 bd-highlight">
      </div>
    </div>
  </div>
</div>

<div class="block">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-lg-7">
      <div class="block-form form-style">
        <%= simple_form_for [@hood, @contract] do |f|%>
          <%= f.input :name %>
          <%= f.input :description, :as => :text, :input_html => { 'rows' => 5, 'cols' => 7 } %>
          <%= f.input :location%>
          <%= f.input :date %>
          <%= f.input :violence_required%>
          <%= f.input :photo, as: :file %>
          <%= f.button :submit, class: "button-card-form" %>
        <% end %>
      </div>
    </div>

    <div class="col-xs-12 col-md-6 col-lg-4">
      <div class="card-product mx-3">
        <img src=<%= @hood.url %> />
        <div class="card-product-infos">
          <div class="block-name-star">
            <h2><%= @hood.name %></h2>
            <div class="stars-new">
              <p class="ml-3">
                <% if (5 - @hood.rating) != 0 %>
                  <% @hood.rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% (5 - @hood.rating).times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                <% else %>
                  <% 5.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                <% end %>
              </p>
            </div>
          </div>

        </div>
        <div class="lvl-violence d-flex justify-content-between">
          <p class="ml-3 mt-5">Aggressivity : </p>
          <div class="ml-3 mt-5">
            <% if (3 - @hood.violence_range) != 0 %>
              <% @hood.violence_range.times do %>
                <i class="fas fa-tint"></i>
              <% end %>
              <% (3 - @hood.violence_range).times do %>
                <i class="fas fa-tint drop-vide"></i>
              <% end %>
            <% else %>
              <% 3.times do %>
                <i class="fas fa-tint"></i>
              <% end %>
            <% end %>
          </div>
        </div>
        <p class="respond mt-5 ml-3"><%= @hood.name %> responds in 1 hour on average.</p>
      </div>
      <div class="link-to-profil mx-3">
        <%= link_to "Return to Hood profile", hood_path(@hood), class:"btn-back-form" %>
      </div>
    </div>
  </div>
</div>

app/views/contracts/show.html.erb
<div class="container">
  <div class="show-box">
    <div class="card mb-3 contract-header borders-rounded-header">
      <div class="justify-content-center">
        <div class="row no-gutters justify-content-center ">
          <p class="file-name">CONTRACT</p>
          <div class="col-md-8 contract-image">
            <% if @contract.photo.attached? %>
              <%= cl_image_tag @contract.photo.key, height: 200, width: 200, crop: :fill %>
            <% else %>
              <%= cl_image_tag("izscg7g1bbr6pngllryx", height: 200, width: 200, crop: :fill) %>
            <% end %>
            <p class="role"><i class="fas fa-boxing-glove $rouge"></i></p>
          </div>
          <%= link_to "Back", hoods_path, class:"btn-back" %>
          <div class="col-md-8">
            <div class="card-body-header">
              <div>
                <h4 class="card-title"><strong><%=@contract.name.capitalize%></strong></h4>
              </div>
              <p class="card-text location"><i class="fas fa-map-marker-alt"></i>  <%= @contract.location.upcase %></p>
              <p class="card-text"><i class="fas fa-euro-sign"></i>  <%=@contract.hood.price%></p>
              <%= link_to @contract.hood.name + "'s profile", hood_path(@hood), class:'button button-rouge' %>
            </div>
          </div>
          <div class="col-md-8">
          </div>
        </div>
      </div>
    </div>
    <div class="row no-gutters justify-content-center">
      <div class="card w-100 borders-rounded">
        <div class="card-body-show">
          <h5 class="card-title">Description: </h5>
          <p class="card-text"><%= @contract.description %></p>
          <div class="violence-date">
            <div class="card-title-block">
              <h5 class="card-title">Violence Required</h5>
              <div class="lvl-violence">
                <div class="mt-2">
                  <% if (3 - @contract.violence_required) != 0 %>
                    <% @contract.violence_required.times do %>
                      <i class="fas fa-tint"></i>
                    <% end %>
                    <% (3 - @contract.violence_required).times do %>
                      <i class="fas fa-tint drop-vide"></i>
                    <% end %>
                  <% else %>
                    <% 3.times do %>
                      <i class="fas fa-tint"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
              <div class="card-title-block">
                <h5 class="card-title">Date</h5>
                <div class="block-content">
                  <%= @contract.date %>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hoods/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1542367235-d0f3b564d16e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2089&q=80);">
  <div class="container ">
    <h1><strong>Hood</strong></h1>
    <p>You have problems, we have <strong>the</strong> solution</p>
    <div class="d-flex align-items-end flex-column bd-highlight mb-3">
      <div class="mt-auto p-2 bd-highlight">
      </div>
    </div>
  </div>
</div>



<!-- FILTRES -->
<div class="container d-flex justify-content-around mt-3">
  <div class="select-violence">
    <div>
      <%= form_tag(hoods_path, method: "get", class:"form-inline") do %>
        <%= label_tag(:query, "Filter by: ", class:"pr-3") %>
         <%= hidden_field_tag :search, params[:search] %>
          <select name="query" class="select-css">
            <option value="">Violence</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <% end %>
          </select>
        </div>
     <div> <%= submit_tag("Search", class:"btn btn-secondary ml-3") %> </div>
  </div>

  <div class="select-price">
    <div class="form-inline">
      <%= form_tag(hoods_path, method: "get" ) do %>
        <% label_tag(:query_price, class:"pr-3") %>
         <%= hidden_field_tag :search, params[:search] %>
          <select name="query_price" class="select-css">
            <option value="">Price</option>
            <option value="1">Croissant</option>
            <option value="2">Decroissant</option>
            <% end %>
          </select>
        </div>
      <div> <%= submit_tag("Search", class:"btn btn-secondary ml-3") %></div>
  </div>
</div>

<!-- FIN DES FILTRES -->



<div class = "container">

  <% if  %>
    <% @hoods.count == 0 %>
    <h5 class="error-title" >Sorry, there are no Hoods in this city: <%= params[:search].to_s %> </h5>
    <h5 class="error-title"> Try an other city</h5>
    <%= link_to "Search again", root_path, class:"btn btn-secondary" %>
  <% else %>
    <h2 class="text-header mt-3 p-3">Our hoods in <%= params[:search].to_s.capitalize %>:</h2>
  <% end %>

  <div class ="row colonne">
    <% @hoods.each do |hood| %>
      <div class ="col-xs-12 col-md-6 col-lg-4">
        <div class ="d-flex justify-content-around">
          <div class ="card mt-3 mb-3 w-200 card-hood">
            <img class="card-img-top card-image" src= <%= hood.url %> alt= 'Photo de chaque hoodman'>
            <div class="card-body">
              <div class="card-price" >
                <p><%= hood.price %>€</p>
              </div>
              <div class="stars">
                <p>
                  <% if (5 - hood.rating) != 0 %>
                    <% hood.rating.times do %>
                      <i class="fas fa-star"></i>
                    <% end %>
                    <% (5 - hood.rating).times do %>
                      <i class="far fa-star"></i>
                    <% end %>
                  <% else %>
                    <% 5.times do %>
                      <i class="fas fa-star"></i>
                    <% end %>
                  <% end %>
                </p>
              </div>
              <h5 class="card-title name-hood"><%= hood.name %></h5>
              <p class="card-text mt-3"><%= hood.skills.capitalize %></p>
              <p class="hood-city"><i class="fas fa-map-marker-alt mr-2"></i><%= hood.city.capitalize %></p>
              <div class="lvl-violence d-flex justify-content-between">
                <p class="mt-2 aggressivity">Aggressivity : </p>
                <div class="mt-2">
                  <% if (3 - hood.violence_range) != 0 %>
                    <% hood.violence_range.times do %>
                      <i class="fas fa-tint"></i>
                    <% end %>
                    <% (3 - hood.violence_range).times do %>
                      <i class="fas fa-tint drop-vide"></i>
                    <% end %>
                  <% else %>
                    <% 3.times do %>
                      <i class="fas fa-tint"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <%= link_to "See more", hood_path(hood), class:"button-card d-flex justify-content-center" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/hoods/show.html.erb
<div class="container">
  <div class="show-box">
    <div class="card mb-3 contract-header borders-rounded-header">
      <div class="justify-content-center">
        <div class="row no-gutters justify-content-center ">
          <p class="file-name">HOOD PROFILE</p>
          <div class="col-md-8 contract-image">
            <img src= <%= @hood.url %> class="card-img" alt="...">
            <p class="role"><i class="fas fa-boxing-glove $rouge"></i></p>
          </div>
          <%= link_to "Back", hoods_path, class:"btn-back" %>
          <div class="col-md-8">
            <div class="card-body-header">
              <div>
                <h4 class="card-title"><strong><%=@hood.name.capitalize%></strong></h4>
              </div>
              <p class="card-text location"><i class="fas fa-map-marker-alt"></i>  <%= @hood.city.upcase %></p>
              <p class="card-text"><i class="fas fa-euro-sign"></i>  <%=@hood.price%></p>
              <%= link_to "Create contract", new_hood_contract_path(@hood), class:"button button-rouge"%>
            </div>
          </div>
        </div>
          <div class="col-md-8">
          </div>
      </div>
    </div>
    <div class="row no-gutters justify-content-center">
      <div class="card w-100 borders-rounded">
        <div class="card-body-show">
          <h5 class="card-title">Description: </h5>
          <p class="card-text description"><%= @hood.description%></p>
          <div class="violence-date">
            <div class="card-title-block">
              <h5 class="card-title">Violence range</h5>
              <div class="lvl-violence">
                <div class="mt-2">
                  <% if (3 - @hood.violence_range) != 0 %>
                    <% @hood.violence_range.times do %>
                      <i class="fas fa-tint"></i>
                    <% end %>
                    <% (3 - @hood.violence_range).times do %>
                      <i class="fas fa-tint drop-vide"></i>
                    <% end %>
                  <% else %>
                    <% 3.times do %>
                      <i class="fas fa-tint"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="card-title-block">
              <h5 class="card-title">Skills</h5>
              <div class="block-content-hood">
                <%= @hood.skills.capitalize %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Lacagoule</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>


  <body>
    <%= render 'shared/navbar' if user_signed_in? %>

    <% unless user_signed_in? %>
      <%= link_to "Log in", new_user_session_path, class:"button-login" %>
    <% end %>

    <%= yield %>
    <%= render 'shared/flashes' %>

    <% unless controller_name == 'pages' && action_name == 'home' %>
      <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="big-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1542367235-d0f3b564d16e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2089&q=80);">
    <div class="container">
      <div class ="col-xs-12 col-md-12 col-lg-12">
      <h1><strong>Welcome to the Hood</strong></h1>
      <p><span id="banner-typed-text"></span></p>
      <p>We have some badass who can do it for you</p>
    </div>
  </div>
  <div class="searchdiv">
    <div class="searchcontainer">
      <%= form_tag(hoods_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search],
        autocomplete: "off",
        placeholder: "Where ?" %>
      <div class="searchbar"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small footer-background">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 pt-3">
        <div class="d-flex justify-content-center">

          <!-- Facebook -->
          <a href="" class="fb-ic">
            <i class="fab fa-facebook-f fa-lg color-item mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a href="" class="tw-ic">
            <i class="fab fa-twitter fa-lg color-item mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Instagram-->
          <a href="" class="ins-ic">
            <i class="fab fa-instagram fa-lg color-item mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Pinterest-->
          <a href="" class="pin-ic">
            <i class="fab fa-pinterest fa-lg color-item fa-2x"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-2 text-white">© 2020 Copyright:
    <a href="#" class="text-color"> LaCagoule.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm <%= action_name == "show" ? "navbarr-light navbar-lewagonn" : "navbar-light navbar-lewagon" %>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_black_hood.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="<%= action_name == "show" ? "item_de_navv" : "item_de_nav" %>">
        <li class="nav-item">
          <%= link_to "Home", hoods_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contracts", contracts_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown ml-1">
          <%= image_tag "https://i.pinimg.com/236x/03/ad/ea/03adeaaa67be045f9d0f0c9d520e896c--mr-bean-beans.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </div>
    </ul>
  </div>
</div>

app/views/shared/_navbarhome.html.erb
<div class="navbar navbar-expand-sm navbarr-light navbar-lewagonn">
  <%= link_to root_path, class:"navbar-brand" do %>
    <%= image_tag "logo_black_hood.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="item_de_navv">
        <li class="nav-item">
          <%= link_to "Home", hoods_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contracts", contracts_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown ml-1">
          <%= image_tag "https://i.pinimg.com/236x/03/ad/ea/03adeaaa67be045f9d0f0c9d520e896c--mr-bean-beans.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </div>
    </ul>
  </div>
</div>